FROM golang:stretch AS builder
WORKDIR /go/src/app
COPY ./go .
ENV GO111MODULE=on
RUN go mod tidy
RUN go build -o server

#final stage
FROM gcr.io/distroless/base
COPY --from=builder /go/src/app/server /app
ENV PORT=8080
ENV ENVS="dev"
ENTRYPOINT [ "/app" ]
CMD [ "/server" ]