# FROM golang:1.18-alpine

# RUN apk update &&  apk add git

# WORKDIR /go/src/app

# ADD ./go .

# RUN go mod tidy

FROM golang:stretch AS builder
WORKDIR /go/src/app
COPY ./go .
ENV GO111MODULE=on
RUN go mod tidy
RUN go build -o server

#final stage
FROM gcr.io/distroless/base
COPY --from=builder /go/src/app/server /app
ENV PORT=${PORT}
ENTRYPOINT [ "/app" ]
CMD [ "/server" ]